config/routes.rb
Rails.application.routes.draw do
  root 'locations#index'
  post 'locations/:id' => 'conditions#create'

  resources :locations do
    resources :garments
  end

  namespace :api do
    namespace :v1 do
      resources :conditions, only: [:create]
    end
  end

  resources :users

  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
end

app/models/location.rb
class Location < ActiveRecord::Base
  include WolfAdvice

  belongs_to :user
  has_many :conditions

  validates :city, presence: true
  validates :state, presence: true
  validates :zip, presence: true, numericality: { only_integer: true }, length: { is: 5 }
  validates :country, presence: true
end

app/controllers/locations_controller.rb
require './config/initializers/geolocation'
require './config/initializers/darksky'

require 'dotenv-rails'
Dotenv.load

class LocationsController < ApplicationController
  include WolfAdvice

  def index
    if user_signed_in?
      @user = current_user
    else
      redirect_to new_user_session_path
    end

    @ip = request.ip
    @geolocation = Geolocation.new(@ip)
    @darksky = Darksky.new(@geolocation.latitude, @geolocation.longitude)
    @current_condition = @darksky
    @wolf_advice = display_wolf_advice


    @locations = Location.where(user_id: @user.id)

    render :index
  end

  def show
    @user = current_user
    @location = Location.find(params[:id])
  end

  def new
    if user_signed_in?
      @location = Location.new
    else
      flash[:notice] = "You must be signed in to create a location."
      redirect_to new_user_session_path
    end
  end

  def create
    @location = Location.new(location_params)
    @location.user = current_user

    if @location.save
      redirect_to location_path(@location)
      flash[:notice] = "Location created."
    else
      flash[:notice] = @location.errors.full_messages.join(', ')
      render :new
    end
  end

  private

  def location_params
    params.require(:location).permit(:user, :city, :state, :zip, :country, :latitude, :longtitude)
  end
end

app/views/locations/index.html.erb
<h1> Hello, <%= current_user.email %>! Let's get you outfitted! </h1>

<div class="weather-info callout primary">
  <div class="greeting">
    <h3>The weather in <%= @geolocation.city %> is: <br></h2>
    <span>High: <%= @darksky.maxtemp.round %> Low: <%= @darksky.mintemp.round %></span><br>
    <span>Chance of precipitation: <%= (@darksky.precipitation * 100).round %>%
          Chance of humidity: <%= (@darksky.humidity * 100).round %>%</span><br>
    <span><%= @darksky.summary %></span>
  </div>
</div>
<br>
<div class="weather-info success callout">
  <div class="wolf-advice-index">
    <div class="wolf-says">
      <h2>The wolf says:</h2>
    </div>
    <%=@wolf_advice%>
  </div>
</div>

<h2> Trying to get dressed for a different location?</h2>
<div class="user-locations success callout">
  <h3>Choose from Your Locations: </h3>
  <ul>
    <% @locations.each do |location| %>
      <li><%= link_to location.city , location_path(location), method: :get %>, <%= location.state %> <%= location.zip %>, <%= location.country %> </li>
    <% end %>
  </ul>
</div>


<h2><%= link_to 'Add a New Location', new_location_path, method: :get %></h2>

app/views/locations/new.html.erb
<h1>Add a New Location</h1>
<h3>Enter street address or fill in the fields below.</h3>
<div id="locationField">
  <input placeholder="Enter new address" id="autocomplete"
           type="text"></input>
</div>

<div class="add-location-form">
  <%= form_for(@location) do |f|%>
        <div class="field">
          <%= f.label :city, "City" %>
          <%= f.text_field :city, id: "locality", disabled: false  %>
        </div>
        <div class="field">
          <%= f.label :state, "State" %>
          <%= f.text_field :state, id: "administrative_area_level_1", disabled: false %>
        </div>
        <div class="field">
          <%= f.label :zip, "Zip" %>
          <%= f.text_field :zip, id: "postal_code", disabled: false %>
        </div>
        <div class="field">
          <%= f.label :country, "Country" %>
          <%= f.text_field :country, id: "country", disabled: false %>
        </div>
        <div class="actions top-padded">
          <%= f.submit "Add Location", class: "search-button" %>
        </div>
    <% end %>
</div>
<script>
  var placeSearch, autocomplete;
  var componentForm = {
       locality: 'long_name',
       administrative_area_level_1: 'short_name',
       country: 'long_name',
       postal_code: 'short_name'
  };

  function initAutocomplete() {
    autocomplete = new google.maps.places.Autocomplete(
      (document.getElementById('autocomplete')),
      {types: ['geocode']});
    autocomplete.addListener('place_changed', fillInAddress);
  }

  function fillInAddress() {
    var place = autocomplete.getPlace();

    for (var component in componentForm) {
      document.getElementById(component).value = '';
      document.getElementById(component).disabled = false;
    }

    for (var i = 0; i < place.address_components.length; i++) {
      var addressType = place.address_components[i].types[0];
      if (componentForm[addressType]){
        var val = place.address_components[i][componentForm[addressType]];
        document.getElementById(addressType).value = val;
      }
    }
  }

  function geolocate() {
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(function(position){
        var geolocation = {
          lat: position.coords.latitude,
          lng: position.coords.longitude
        };
        var circle = new google.maps.Circle({
          center: geolocation,
          radius: position.coords.accuracy
        });
        autocomplete.setBounds(circle.getBounds())
      });
    }
  }

</script>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?libraries=places&key=<%= ENV['GOOGLE_MAPS_GEOCODING_API_KEY']%>&callback=initAutocomplete"></script>
</script>

<div class="back-link">
  <h3><%= link_to 'Return Home', locations_path, method: :get %></h3>
</div>

app/views/locations/show.html.erb
  <h1><%= @location.city %>, <%= @location.state %>, <%= @location.zip %> <%= @location.country %> </h1>
  <div class="get-weather user-buttons"><h3>The wolf has you covered. Click for wolf advice.</h3><%= button_to 'Wolf Advice', locations_path(@location)  %></div>
<br><br>
<div class="weather-info-show success callout">
  <div class="high"></div> <div class="low"></div>
  <div class="precipitation"></div> <div class="humidity"></div>
  <div class="summary"></div>
</div>
<br>
<div class="wolf-image">
  <%= image_tag("/assets/wolfclothing.jpg") %>
</div>
<div class="clothing-suggestions success callout">
  <div class="wolf-says">
    <h2>The wolf says: </h2>
  </div>

  <div class="wolf-advice">
  </div>
</div>
<div class="back-link top-padded">
  <%= link_to 'Return Home', locations_path, method: :get  %>
</div>
<div id="zip" hidden="true"><%= @location.zip %></div>